---
title: "Invaded Range"
output: 
  rmarkdown::html_vignette
params:
  show_code: TRUE
author: 
    - "Lilah Shtino^[Temple University, lilah.shtino@temple.edu]"
    - "Matthew R. Helmus^[Temple University, mrhelmus@temple.edu]"
date: "`r format(Sys.time(), '%d %B %Y')`"
vignette: >
  %\VignetteIndexEntry{invaded_range}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setting figure files as png, include = FALSE}
# The YAML parameter `show_code` controls whether code is shown (via `echo`) for the code chunks.
knitr::opts_chunk$set(dev = "png", dpi = 100, echo = params$show_code)
```

```{r packages and data, include = params$show_code, message = FALSE, warning = FALSE}
# attaching necessary packages
library(lydemapr)
library(sf)
library(tidyverse)
library(tigris)
```

## Citation
Keller, J., S De Bona, & MR Helmus. Leveraging spatial scale and temporal variation to track the spread rate of invasive spotted lanternflies (Lycorma delicatula). NeoBiota, 106: 287-307. https://doi.org/10.3897/neobiota.106.177041

```{r sampling effort, results = "asis", fig.cap = "Sampling effort based on invaded range"}
knitr::kable(sampling_effort())
```


```{r results = "asis", fig.cap = "Scale selection for α hulls by Youden's J"}
scale_selection()
```


```{r pressure, echo=FALSE, fig.cap = "Output of the `map_alphahull()` function for the 2025 biological year"}
map_alphahull(bio_year = 2025)
```
